Updated Alpine to 3.12. Updated Nginx to 1.19.6

diff --git a/php7.4-fpm-nginx/Dockerfile b/php7.4-fpm-nginx/Dockerfile
--- a/php7.4-fpm-nginx/Dockerfile
+++ b/php7.4-fpm-nginx/Dockerfile
@@ -1,4 +1,4 @@
-FROM php:7.4-fpm-alpine3.10
+FROM php:7.4-fpm-alpine3.12
 
 LABEL maintainer="Touch4IT <admin@touch4it.com>"
 
@@ -14,28 +14,25 @@ ENV PHP_UPLOAD_MAX_FILESIZE 32M
 ENV PHP_POST_MAX_SIZE 32M
 
 RUN apk --update add --no-cache \
-		acl \
-		bash \
-		freetype-dev \
-		gettext-dev \
-		git \
-		icu-dev \
-		libjpeg-turbo-dev \
-		libpng-dev \
-		libzip-dev \
-		oniguruma-dev \
-		php7-dom \
-		php7-xml \
-		postgresql-dev \
-		zip \
-		grep \
-	&& docker-php-ext-configure gd \
-		--with-jpeg \
-		--with-freetype \
-	&& docker-php-ext-configure pgsql \
-		-with-pgsql=/usr/local/pgsql \
-	&& docker-php-ext-configure zip \
-		--with-zip \
+    acl \
+    bash \
+    freetype-dev \
+    gettext-dev \
+    git \
+    icu-dev \
+    libjpeg-turbo-dev \
+    libpng-dev \
+    libzip-dev \
+    oniguruma-dev \
+    php7-dom \
+    php7-xml \
+    postgresql-dev \
+    zip \
+    grep
+
+RUN docker-php-ext-configure gd --with-jpeg --with-freetype \
+	&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
+	&& docker-php-ext-configure zip --with-zip \
 	&& docker-php-ext-install \
 		bcmath \
 		exif \
@@ -73,12 +70,12 @@ RUN curl -sS https://getcomposer.org/installer | php \
 # NGINX
 #
 
-ENV NGINX_VERSION 1.16.1
-ENV NJS_VERSION   0.3.5
-ENV PKG_RELEASE 1
+ENV NGINX_VERSION 1.19.6
+ENV NJS_VERSION   0.5.0
+ENV PKG_RELEASE   1
 
 RUN set -x \
-	# create nginx user/group first, to be consistent throughout docker variants
+    # create nginx user/group first, to be consistent throughout docker variants
     && addgroup -g 101 -S nginx \
     && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
     && apkArch="$(cat /etc/apk/arch)" \
@@ -91,29 +88,25 @@ RUN set -x \
     " \
     && case "$apkArch" in \
         x86_64) \
-			# arches officially built by upstream
+            # arches officially built by upstream
             set -x \
             && KEY_SHA512="e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a *stdin" \
             && apk add --no-cache --virtual .cert-deps \
                 openssl \
             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
             && if [ "$(openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout | openssl sha512 -r)" = "$KEY_SHA512" ]; then \
-                 echo "key verification succeeded!"; \
-                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
-               else \
-                 echo "key verification failed!"; \
-                 exit 1; \
-               fi \
-            && printf "%s%s%s\n" \
-                "https://nginx.org/packages/alpine/v" \
-                `egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release` \
-                "/main" \
-            | tee -a /etc/apk/repositories \
+                echo "key verification succeeded!"; \
+                mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+            else \
+                echo "key verification failed!"; \
+                exit 1; \
+            fi \
             && apk del .cert-deps \
+            && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
             ;; \
         *) \
-			# we're on an architecture upstream doesn't officially build for
-			# let's build binaries from the published packaging sources
+            # we're on an architecture upstream doesn't officially build for
+            # let's build binaries from the published packaging sources
             set -x \
             && tempDir="$(mktemp -d)" \
             && chown nobody:nobody $tempDir \
@@ -139,28 +132,25 @@ RUN set -x \
                 && cd ${tempDir} \
                 && hg clone https://hg.nginx.org/pkg-oss \
                 && cd pkg-oss \
-                && hg up -r 429 \
+                && hg up ${NGINX_VERSION}-${PKG_RELEASE} \
                 && cd alpine \
                 && make all \
                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
                 " \
-            && echo "${tempDir}/packages/alpine/" >> /etc/apk/repositories \
             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
             && apk del .build-deps \
+            && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages \
             ;; \
     esac \
-    && apk add --no-cache $nginxPackages \
-	# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+    # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
     && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
     && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
-	# remove the last line with the packages repos in the repositories file
-    && sed -i '$ d' /etc/apk/repositories \
-	# Bring in gettext so we can get `envsubst`, then throw
-	# the rest away. To do this, we need to install `gettext`
-	# then move `envsubst` out of the way so `gettext` can
-	# be deleted completely, then move `envsubst` back.
+    # Bring in gettext so we can get `envsubst`, then throw
+    # the rest away. To do this, we need to install `gettext`
+    # then move `envsubst` out of the way so `gettext` can
+    # be deleted completely, then move `envsubst` back.
     && apk add --no-cache --virtual .gettext gettext \
     && mv /usr/bin/envsubst /tmp/ \
     \
@@ -174,10 +164,12 @@ RUN set -x \
     && apk add --no-cache $runDeps \
     && apk del .gettext \
     && mv /tmp/envsubst /usr/local/bin/ \
-	# Bring in tzdata so users could set the timezones through the environment
-	# variables
+    # Bring in tzdata so users could set the timezones through the environment
+    # variables
     && apk add --no-cache tzdata \
-	# forward request and error logs to docker log collector
+    # Bring in curl and ca-certificates to make registering on DNS SD easier
+    && apk add --no-cache curl ca-certificates \
+    # forward request and error logs to docker log collector
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log
 
