Add Imagick 3.8.0

diff --git a/php8/php8.2-apache/Dockerfile b/php8/php8.2-apache/Dockerfile
--- a/php8/php8.2-apache/Dockerfile
+++ b/php8/php8.2-apache/Dockerfile
@@ -10,77 +10,94 @@ COPY 000-default.conf $APACHE_CONFDIR/sites-available/000-default.conf
 COPY php-override.ini $PHP_INI_DIR/conf.d/php-override.ini
 
 RUN apt-get update \
-	&& apt-get install -y --no-install-recommends \
-		acl \
-		bash \
-		cron \
-		curl \
-		gettext \
-		git \
-		libicu-dev \
-		libjpeg-dev \
-		libfreetype6-dev \
-		libmagickwand-dev \
-		libonig-dev \
-		libpng-dev \
-		libpq-dev \
-		libwebp-dev \
-		libxml2-dev \
-		libzip-dev \
-		zip \
-		zlib1g-dev \
-		grep \
-	&& apt-get clean \
-	&& rm -rf /var/lib/apt/lists/*
+  && apt-get install -y --no-install-recommends \
+    acl \
+    bash \
+    cron \
+    curl \
+    gettext \
+    git \
+    libicu-dev \
+    libjpeg-dev \
+    libfreetype6-dev \
+    libmagickwand-dev \
+    libonig-dev \
+    libpng-dev \
+    libpq-dev \
+    libwebp-dev \
+    libxml2-dev \
+    libzip-dev \
+    zip \
+    zlib1g-dev \
+    grep \
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/*
 
 #
 # CRON
 #
 
 RUN mkdir -m 0644 -p /etc/cron.d \
-	&& mkdir -m 0644 -p /var/log/cron \
-	&& touch /var/log/cron/cron.log
+  && mkdir -m 0644 -p /var/log/cron \
+  && touch /var/log/cron/cron.log
 
 #
 # COMPOSER
 #
 
 RUN curl -sS https://getcomposer.org/installer | php \
-	&& mv composer.phar /usr/local/bin/composer \
-	&& composer self-update
+  && mv composer.phar /usr/local/bin/composer \
+  && composer self-update
 
 #
 # PHP extensions
 #
 
+# Install specific version of Imagick from source
+RUN set -xe \
+  && cd /tmp \
+  # Download specific version of Imagick PECL extension
+  && curl -sS https://pecl.php.net/get/imagick-3.8.0.tgz --output imagick-3.8.0.tgz \
+  && tar -xzf imagick-3.8.0.tgz \
+  && cd imagick-3.8.0 \
+  # Configure and install
+  && phpize \
+  && ./configure \
+  && make \
+  && make install \
+  # Enable the extension
+  && docker-php-ext-enable imagick \
+  # Clean up
+  && cd .. \
+  && rm -rf imagick-3.8.0 imagick-3.8.0.tgz
+
 RUN \
-  # Enable imagick when https://github.com/Imagick/imagick/issues/643 is solved
   # pecl install imagick \
   # && docker-php-ext-enable imagick \
-	docker-php-ext-configure gd \
-		--with-freetype \
-		--with-jpeg \
-		--with-webp \
-	&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
-	&& docker-php-ext-configure bcmath --enable-bcmath \
-	&& docker-php-ext-install \
-		bcmath \
-		exif \
-		gd \
-		gettext \
-		intl \
-		mysqli \
-		opcache \
-		pdo_mysql \
-		pdo_pgsql \
-		pgsql \
-		zip
+  docker-php-ext-configure gd \
+    --with-freetype \
+    --with-jpeg \
+    --with-webp \
+  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
+  && docker-php-ext-configure bcmath --enable-bcmath \
+  && docker-php-ext-install \
+    bcmath \
+    exif \
+    gd \
+    gettext \
+    intl \
+    mysqli \
+    opcache \
+    pdo_mysql \
+    pdo_pgsql \
+    pgsql \
+    zip
 
 #
 # Apache
 #
 
 RUN a2enmod rewrite \
-	&& a2enmod http2 \
-	&& ln -sf /dev/stdout /var/log/apache2/access.log \
-	&& ln -sf /dev/stderr /var/log/apache2/error.log
+  && a2enmod http2 \
+  && ln -sf /dev/stdout /var/log/apache2/access.log \
+  && ln -sf /dev/stderr /var/log/apache2/error.log
diff --git a/php8/php8.3-fpm-apache/Dockerfile b/php8/php8.3-fpm-apache/Dockerfile
--- a/php8/php8.3-fpm-apache/Dockerfile
+++ b/php8/php8.3-fpm-apache/Dockerfile
@@ -51,6 +51,25 @@ RUN curl -sS https://getcomposer.org/installer | php \
 #
 # PHP extensions
 #
+
+# Install specific version of Imagick from source
+RUN set -xe \
+  && cd /tmp \
+  # Download specific version of Imagick PECL extension
+  && curl -sS https://pecl.php.net/get/imagick-3.8.0.tgz --output imagick-3.8.0.tgz \
+  && tar -xzf imagick-3.8.0.tgz \
+  && cd imagick-3.8.0 \
+  # Configure and install
+  && phpize \
+  && ./configure \
+  && make \
+  && make install \
+  # Enable the extension
+  && docker-php-ext-enable imagick \
+  # Clean up
+  && cd .. \
+  && rm -rf imagick-3.8.0 imagick-3.8.0.tgz
+
 RUN \
   # Enable imagick when https://github.com/Imagick/imagick/issues/643 is solved
   # pecl install imagick \
diff --git a/php8/php8.4-fpm-nginx/Dockerfile b/php8/php8.4-fpm-nginx/Dockerfile
--- a/php8/php8.4-fpm-nginx/Dockerfile
+++ b/php8/php8.4-fpm-nginx/Dockerfile
@@ -39,6 +39,26 @@ RUN apk --update add --no-cache \
   zip \
   ${PHPIZE_DEPS}
 
+# Install ImageMagick from source with compatible version for PHP 8.3/8.4
+RUN set -xe \
+  && apk add --no-cache \
+    imagemagick \
+    imagemagick-dev \
+    # Add any other dependencies needed
+  \
+  && cd /tmp \
+  && curl -sS https://pecl.php.net/get/imagick-3.8.0.tgz --output imagick-3.8.0.tgz \
+  && tar -xzf imagick-3.8.0.tgz \
+  && cd imagick-3.8.0 \
+  && phpize \
+  && ./configure \
+  && make \
+  && make install \
+  && docker-php-ext-enable imagick \
+  # Clean up
+  && cd .. \
+  && rm -rf imagick-3.8.0 imagick-3.8.0.tgz
+
 RUN \
   # Enable imagick when https://github.com/Imagick/imagick/issues/643 is solved
   # pecl install imagick \
